<?xml version="1.0"?>
<robot name="sensor_r430" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <!-- The following values are approximate, and the camera node
   publishing TF values with actual calibrated camera extrinsic values -->
  <xacro:property name="r430_cam_depth_to_left_ir_offset" value="-0.021"/>
  <xacro:property name="r430_cam_depth_to_right_ir_offset" value="0.029"/>
  <xacro:property name="r430_cam_depth_to_fisheye_offset" value="0.044"/>

  <!-- The following values model the aluminum peripherial case for the
    R430 camera, with the camera joint represented by the actual
    peripherial camera tripod mount -->
  <xacro:property name="r430_cam_width" value="0.100"/>
  <xacro:property name="r430_cam_depth" value="0.025"/>
  <xacro:property name="r430_cam_height" value="0.025"/>
  <xacro:property name="r430_cam_mount_from_center_offset" value="0.0"/>

  <!-- The following offset is relative the the physical R430 camera peripherial
    camera tripod mount -->
  <xacro:property name="r430_cam_depth_px" value="0.00"/>
  <xacro:property name="r430_cam_depth_py" value="-0.0115"/>
  <xacro:property name="r430_cam_depth_pz" value="0.0"/>

  <xacro:macro name="sensor_r430" params="prefix parent prefix_topic:='front_rgbd_camera' *origin">

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${prefix}_camera_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}_camera_link" />
    </joint>

    <link name="${prefix}_camera_link">
      <visual>
      <!-- origin xyz="0 ${-r430_cam_mount_from_center_offset} ${r430_cam_height/2}" rpy="${M_PI/2} 0 ${M_PI/2}"/ -->
      <origin xyz="0 ${-r430_cam_mount_from_center_offset} 0" rpy="0 0 0"/>
        <geometry>
          <!-- box size="${r430_cam_width} ${r430_cam_height} ${r430_cam_depth}"/ -->
          <mesh filename="package://robotnik_sensors/meshes/intel_r430.dae" />
        </geometry>
        <material name="aluminum">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${-r430_cam_depth/2} 0.0 0.0" rpy="0 0 0"/>
        <geometry>
        <box size="${r430_cam_depth} ${r430_cam_width} ${r430_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

    <!-- camera depth joints and links -->
    <joint name="${prefix}_camera_depth_joint" type="fixed">
      <origin xyz="${r430_cam_depth_px} ${r430_cam_depth_py} ${r430_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${prefix}_camera_link"/>
      <child link="${prefix}_camera_depth_frame" />
    </joint>
    <link name="${prefix}_camera_depth_frame"/>

    <joint name="${prefix}_camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${prefix}_camera_depth_optical_frame" />
    </joint>
    <link name="${prefix}_camera_depth_optical_frame"/>

    <!-- camera left IR joints and links -->
    <joint name="${prefix}_camera_left_ir_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${prefix}_camera_left_ir_frame" />
    </joint>
    <link name="${prefix}_camera_left_ir_frame"/>

    <joint name="${prefix}_camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_left_ir_frame" />
      <child link="${prefix}_camera_left_ir_optical_frame" />
    </joint>
    <link name="${prefix}_camera_left_ir_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="${prefix}_camera_right_ir_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${prefix}_camera_right_ir_frame" />
    </joint>
    <link name="${prefix}_camera_right_ir_frame"/>

    <joint name="${prefix}_camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_right_ir_frame" />
      <child link="${prefix}_camera_right_ir_optical_frame" />
    </joint>
    <link name="${prefix}_camera_right_ir_optical_frame"/>

    <!-- camera fisheye joints and links -->
    <joint name="${prefix}_camera_fisheye_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_fisheye_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${prefix}_camera_fisheye_frame" />
    </joint>
    <link name="${prefix}_camera_fisheye_frame"/>

    <joint name="${prefix}_camera_fisheye_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_fisheye_frame" />
      <child link="${prefix}_camera_fisheye_optical_frame" />
    </joint>
    <link name="${prefix}_camera_fisheye_optical_frame"/>


  <!-- RGBD sensor for simulation, same as Kinect -->
  <sensor_r430_gazebo/>

  </xacro:macro>

   <xacro:macro name="sensor_r430_gazebo">

    <!-- gazebo reference="${prefix}_rgb_base_link" -->
    <gazebo reference="${prefix}_camera_link">
      <sensor type="depth" name="${prefix}_depth_sensor">
        <always_on>true</always_on>
        <update_rate>15.0</update_rate>
        <camera>
          <horizontal_fov>${91.2*M_PI/180.0}</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.3</near>
            <far>10.0</far>
          </clip>
        </camera>
        <plugin name="${prefix}_controller" filename="libgazebo_ros_openni_kinect.so">
          <cameraName>${prefix_topic}</cameraName>
          <alwaysOn>true</alwaysOn>
          <updateRate>10</updateRate>
          <imageTopicName>rgb/image_raw</imageTopicName>
          <depthImageTopicName>depth/image_raw</depthImageTopicName>
          <pointCloudTopicName>depth/points</pointCloudTopicName>
          <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
          <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
          <frameName>/${prefix}_camera_depth_optical_frame</frameName>
          <baseline>0.1</baseline>
          <distortion_k1>0.0</distortion_k1>
          <distortion_k2>0.0</distortion_k2>
          <distortion_k3>0.0</distortion_k3>
          <distortion_t1>0.0</distortion_t1>
          <distortion_t2>0.0</distortion_t2>
          <pointCloudCutoff>0.4</pointCloudCutoff>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>


</robot>
