bool is_calculating             # true when node is calculating the odometry parameters
float32 remaining_time          # remaining time in seconds for obtaining odometry values

float32 left_radius             # radius of the left wheel in meters
float32 right_radius            # radius of the right wheel in meters
float32 wheels_distance         # distance between the two wheels of the robot in meters